### ISSUE TITLE
ADTTE vignette & template

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralonco#14]

**Comment by rossfarrugia** [comment]
if anybody particularly wanted to work on this let me know but otherwise i'll take it as having drafted the workflow it should be easier for me to set these up.

**Comment by rossfarrugia** [comment]
Include some extra non standard examples like Time to Progression

**Comment by rossfarrugia** [comment]
@bundfussr do we need an admiralonco version of the `list_tte_source_objects` code at https://github.com/pharmaverse/admiral/blob/main/R/derive_param_tte.R so that i can create the equivalent onco table as per https://pharmaverse.github.io/admiral/articles/bds_tte.html#pre-defined-time-to-event-source-objects? if so any ideas where i should put it?

**Comment by rossfarrugia** [comment]
yes makes sense @bundfussr, let's go for a similar convention to what Thomas suggests for https://github.com/pharmaverse/admiral/issues/1205. Are you ok to make an admiral issue for this and make the required updates please? https://github.com/pharmaverse/admiral/pull/1210 might help here. i've drafted the ADTTE vignette, but would need this, our test ADRS, and onco_tte_sources from Matt before i can test it and get it ready for review

**Comment by rossfarrugia** [comment]
@bundfussr should https://github.com/pharmaverse/admiralonco/issues/31 actually be called `tte_sources` instead of `onco_tte_sources` then as well? or could the helper object name also be an argument we pass to `list_tte_source_objects()`?

**Comment by bundfussr** [comment]
@rossfarrugia , yes, the title is a bit misleading. We do not need to create a new class. We just want to create some `tte_source` objects. I assume they should be used as examples because their definition includes the `PARAMCD` value, which is company specific. I would expect that the major part of `tte_source` objects is defined at company level. I have added this task to the oncology issue at admiralroche.

**Comment by bundfussr** [comment]
I have created https://github.com/pharmaverse/admiral/issues/1212 for the `list_tte_source_objects()` update.
