### ISSUE TITLE
ADTR vignette & template

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralonco#16]

**Comment by HinalPat** [comment]
@bundfussr https://github.com/pharmaverse/admiralonco/blob/devel/vignettes/adtr.Rmd ready to add template code.

**Comment by bundfussr** [comment]
@HinalPat , thanks.

We should not add directly to `devel` but use feature branches (see https://pharmaverse.github.io/admiraldev/devel/articles/git_usage.html#working-with-feature-branches).

I'll create a feature branch and remove the file from devel. We need to release admiralonco soon (next week) because the latest admiral version breaks admiralonco. Thus the file should not be in devel as it is unlikely that we will complete it this week.
