### ISSUE TITLE
New helper function: filter_pd

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#18]
### Feature Idea

filter_pd - to filter input dataset to only include source parameter records up to and including first PD to then provide these filtered records to the downstream derivations, such as BOR or checking whether patient is a responder.  

### Relevant Input

Input would be ADRS dataset 

### Relevant Output

Output would be a subset of these records only including the source_param records and only keeping those occurring up to and including first PD (where the date comes from the ADT of the source_param_pd records)

### Reproducible Example/Pseudo Code

```
filter_pd(
  dataset,
  filter_source,
  source_pd,
  source_datasets,
  subject_keys = vars(STUDYID, USUBJID)
)
```

Note: for source_pd a date_source() object is expected. See https://pharmaverse.github.io/admiral/reference/derive_param_tte.html as an example of how this works.

**Comment by teckla-gsk** [comment]
@rossfarrugia a few questions on this; I think the expected input dataset would be SDTM.RS v. ADRS because from the specs on box and experience the params in adrs would already have been derived and would include best overall, best confirmed...e.t.c unless the expectation is that the RESP/RSP parameter would keep the responses at all visits such as would be in SDTM. I do not know how common it is that all response assessment visit be kept in adrs? I suppose if designed appropriately the filter could be used with either ADaM or SDTM source ....
second question; what is the purpose of the suggested param source datasets? Is it expected that this could be source from multiple domain datasets with comparison of PD dates or is the expectation that it would always be from an rs source be it ADaM or SDTM?

**Comment by rossfarrugia** [comment]
thanks both! on the suggestion to raise up to admiral core as a more generic function - i agree that could be an option over time but lets just start with `filter_pd` here for now, as there's so much priority work ongoing in admiral core for the next release, and i don't want to delay getting this piece for admiralonco for now as so many other functions will rely on it.

**Comment by teckla-gsk** [comment]
Hi @bundfussr what am I missing here because from the comment above, making use of derive_vars_merged this can be implemented as below, with only the two extra lines on filter and select. Is the goal here to wrap this function? 
 derive_vars_merged(
    select(adlb,STUDYID,USUBJID,ADT),
    #adlb,
    dataset_add = adrs,
    by_vars = vars(STUDYID, USUBJID),
    order = vars(ADT),
    new_vars = vars(temp_ADT = ADT),
    filter_add = PARAMCD == "OVR" & AVALC == "PD" ,
    mode = "FIRST"
  ) %>% 
   filter(ADT<=temp_ADT) %>% 
   select(-temp_ADT)

**Comment by bundfussr** [comment]
@teckla-gsk , I am not sure if your question below is still relevant as it is not in github anymore.

>Hi [@bundfussr](https://github.com/bundfussr) what am I missing here because from the comment above, making use of derive_vars_merged this can be implemented as below, with only the two extra lines on filter and select. Is the goal here to wrap this function?
derive_vars_merged(
select(adlb,STUDYID,USUBJID,ADT),
#adlb,
dataset_add = adrs,
by_vars = vars(STUDYID, USUBJID),
order = vars(ADT),
new_vars = vars(temp_ADT = ADT),
filter_add = PARAMCD == "OVR" & AVALC == "PD" ,
mode = "FIRST"
) %>%
filter(ADT<=temp_ADT) %>%
select(-temp_ADT)

The code looks almost fine to me apart from two points.

- All variables of the input dataset should be kept, i.e., the `select()` call in the first argument should be removed.
- In the main functions we have replaced `source_param` with `filter_source`. We should do it for `filter_pd()` as well. `filter_source` should be applied to the input dataset (before calling `derive_vars_merged`) and `filter_add` should be set to `filter` provided by `source_pd`.

**Comment by teckla-gsk** [comment]
@bundfussr  cool, I will wrap it with filter_source instead, the select was just for demonstration so yes, I agree on it not being in the function
