### ISSUE TITLE
Confirmation of response rules & helper function

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#19]
### Feature Idea

confirmation of response - needs more discussion around whether this is something more generic that could live in admiral core if it’s just a case of enabling comparison of dates between 2 records. Or maybe due to the complexity we should just do something more targeted in admiralonco. We need to understand possible different ways of doing this from GSK/Amgen such as allowing for multiple NEs, before we can develop a suitable helper function.

### Relevant Input

NA

### Relevant Output

NA

### Reproducible Example/Pseudo Code

NA

**Comment by rossfarrugia** [comment]
@bundfussr @amitjaingsk @sgorm123 i would appreciate if the 3 of you could meet at some point over the next couple of weeks to discuss this and come up with a proposal of what we first build for this in admiral or admiralonco.

Stephen - feel free to bring in Catherine here from Amgen but i don't think we have her github ID yet so i couldn't tag her.

**Comment by rossfarrugia** [comment]
p.s. i know we don't yet have the collaboration agreement in place so the usual proviso goes here of just advising around general flexibility needed please, without telling the actual specs.

**Comment by amitjaingsk** [comment]
> @bundfussr @amitjaingsk @sgorm123 i would appreciate if the 3 of you could meet at some point over the next couple of weeks to discuss this and come up with a proposal of what we first build for this in admiral or admiralonco.
> 
> Stephen - feel free to bring in Catherine here from Amgen but i don't think we have her github ID yet so i couldn't tag her.

> @bundfussr @sgorm123 @rossfarrugia Thank you Ross, I think this is a key derivation for ADRS and RECIST1.1 , so suggest to have a separate function for it. Happy to meet @bundfussr @sgorm123. How about 19Apr, 9-10am or 10:30-11:00am EST, mostly open on 21st after 10:00am EST? Please let me know...

**Comment by bundfussr** [comment]
@amitjaingsk , @sgorm123 , I am on vacation from 13th to 20th April. I will sent an invite for the 21st. Please feel free to modify and add others.

**Comment by bundfussr** [comment]
Parameters required for confirmation criteria in derive_param_confirmed_* functions

- number of NEs between two CRs or PRs for confirmation allowed
- accept one SD for confirmed PR (see page 19 of https://ctep.cancer.gov/protocoldevelopment/docs/recist_guideline.pdf?msclkid=f2c721f6c17b11eca78ee886f75c56af)
- number of yy days apart
- number of xx days after treatment start

Other cases to consider:
- Do not separate NE and missing but assign AVALC = 'NE' for both. (add a boolean parameter for this)
- ND should be mapped to AVALC = 'ND' (we could add "Else set to 'ND', if all observations fulfill AVALC = 'ND' (the patient has no disease at baseline (target and non-target))" to the specs)
- mapping AVALC to AVAL (add a parameter which expects a function which defined the mapping)

**Comment by bundfussr** [comment]
@ljin22 , thanks for your feedback.

At Roche CR, PR is not considered as PD. It depends on the assessments after PR. For example if the complete sequence is CR, PR, CR, it would be considered as PR at the second assessment.

However, the document you referred to suggests to handle this case differently. I think we should consider it for our implementation. What about the following?

- For the first step (restricting observations up to first PD (see https://github.com/pharmaverse/admiralonco/issues/24)) we offer an option to restrict the observations up to the first worsening from CR, e.g., the sequence CR, PR, CR would be restricted to CR, PR.
- For the definition of `AVALC = "PD"` we offer an option to define "PD" as `AVALC == "PD"` or `AVALC %in% c("PR", "SD")` and there exists an observation before with `AVALC == "CR"`. For example the in the sequence CR, PR the PR assessment would be considered as PD.

Would this meet your requirements?

Regarding your second point, we could add an option to set ADT to the date of the confirmation assessment instead of the date of the first assessment. Does this make sense?

**Comment by rossfarrugia** [comment]
@bundfussr @ljin22 in my experience investigators (and IRCs) would not only compare a scan vs baseline but they're also aware of the past assessments for a patient so in this case if the tumor has grown since last visit (even though still may have shrunk overall vs baseline) then they should enter PD. So it seems more of a data cleaning piece to me.

Also you could argue that this would need to be covered in the identification of PD (Step 3 in our ADRS workflow doc)? As you wouldn't want the patient to look like they haven't had a PD in some ADaM parameters like PFS and then their BOR show as PD.

**Comment by rossfarrugia** [comment]
@bundfussr i guess we need to find a way to include this option then. do we assume then that some companies are ok with having a patient with confirmed BOR=PD but a PFS no event? if so then i agree it could be catered for in the confirmed BOR function and happy for you all to agree the best strategy to do this. i can review after PHUSE and give input as useful.

**Comment by rossfarrugia** [comment]
See https://github.com/pharmaverse/admiralonco/issues/30 for the new function, so i will close this discussion issue now.
