### ISSUE TITLE
General Issue: Add new vignette and template for using `admiral::derive_extreme_event()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#234]
### Background Information

A new vignettes and template should be added to show how to derive endpoints using `admiral::derive_extreme_event()` (see https://github.com/pharmaverse/admiral/issues/1960).

**Comment by rossfarrugia** [comment]
Decisions from team meeting yesterday (FYI @HinalPat and @manciniedoardo as this fits with our discussions last week):

- Add the new more generic `admiral::derive_extreme_event()` usage options as a separate vignette to show how advanced users could have the option to change their response criteria implementations, with an example of non-standard RECIST 1.1
- Keep the original ADRS vignette and template as it was and don't plan to deprecate the current admiralonco functions
- On site home page clarify the 2 options, e.g. if you want to follow RECIST 1.1 for solid tumor with some minimal flexibilities then use the original ADRS vignette, otherwise you can explore our more advanced user vignette that allows full user control to build different response criteria rules - where more examples will be added over time.
- iRECIST (and Heme criteria) - plan to add extra examples to the vignette and new templates for these for Q4 release instead, as we'll have this foundation then to build upon
- ADRS minor bug fix spotted: please raise a separate issue for this detailing the bug for our user community and then we can fix separately with added extra unit tests to cover this for future

@bundfussr feel free to add me as a reviewer along with @amitjaingsk once the PR is updated for this strategy.
